CREATE DATABASE LIBRARY
GO

USE LIBRARY
GO

CREATE TABLE BOOKS(
Id INT PRIMARY KEY IDENTITY(1,1),
Title VARCHAR(50) NOT  NULL,
AuthorId INT NOT NULL,
Quantity INT,
AvailableQty INT)
GO

CREATE TABLE Author(
AuthorID INT PRIMARY KEY IDENTITY(1,1),
AName VARCHAR(50))
GO

CREATE TABLE BorrowedBooks(
Id INT IDENTITY(1,1),
BorrowedId INT,
BookId INT,
TakenDate DATE)
GO
CREATE TABLE [User](
UserId INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50),
Email VARCHAR(250),
Password VARCHAR(100))

GO